import { ServiceDetail, GalleryItem, StatItem } from './types';

export const STATISTICS: StatItem[] = [
  {
    id: 'experience',
    value: 15,
    suffix: '+',
    label: 'Years Active',
    description: 'Serving Hamilton & Southern Ontario with pride.',
  },
  {
    id: 'projects',
    value: 1420,
    suffix: '+',
    label: 'Completed Projects',
    description: 'Custom luxury bathrooms, spa setups, & custom homes.',
  },
  {
    id: 'clients',
    value: 99.8,
    suffix: '%',
    label: 'Client Satisfaction',
    description: 'Honest transparent pricing & master craftsmanship.',
  },
  {
    id: 'regions',
    value: 7,
    suffix: '',
    label: 'Cities Serviced',
    description: 'From Burlington & Oakville to Lynden & Ancaster.',
  },
];

export const SERVICES_DATA: ServiceDetail[] = [
  {
    id: 'kitchens',
    title: 'Kitchen Plumbing & Renovations',
    subtitle: 'High-end custom builds and luxury finishes',
    icon: 'CookingPot',
    description: 'The kitchen is the heart of your home, demanding flawless design and functional excellence. We collaborate with builders, interior designers, and homeowners to engineer bespoke culinary spaces featuring premier gas fittings, luxury faucet systems, custom appliance connections, and bulletproof under-sink filtration networks.',
    benefits: [
      'Masterful rough-in engineering for absolute structural alignment',
      'Advanced reverse osmosis & premium water filtration integrations',
      'Seamless luxury faucet, pot-filler, and farmhouse sink fittings',
      'Whisper-quiet disposal unit and premium dishwashing layout lines',
    ],
    process: [
      'In-Depth Plan Review & Architectural Consultation',
      'Precision Demolition & Behind-The-Wall Plumbing Layouts',
      'Under-Floor Line Testing & Rough-in Inspections',
      'Polished Trim Installations & Visual Flow Inspection',
    ],
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=1200',
  },
  {
    id: 'bathrooms',
    title: 'Luxury Bathroom Systems',
    subtitle: 'Custom spa designs and five-star wet rooms',
    icon: 'ShowerHead',
    description: 'Transform your daily ritual with high-end, professionally engineered bathrooms. From custom linear-drain tile layouts, freestanding tubs with floor-mounted fillers, to custom dual-shower rain systems, our master plumbing craftsmanship delivers structural integrity that lasts a lifetime.',
    benefits: [
      'Floor-mounted fillers & freestanding tub geometric alignment',
      'Multi-jet rain shower grids with pressure-balancing valves',
      'Custom wall-hung toilets & concealed water closet systems',
      'Waterproof wet-room engineering to avoid foundational leakage',
    ],
    process: [
      '3D Piping Design & Component Planning',
      'Wall-Framing Assessment & Drain Line Leveling',
      'Hydrostatic Pressure Valve & Waterproofing Testing',
      'Trim Assembly, Seal Inspection, and Thermal Temperature Check',
    ],
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&q=80&w=1200',
  },
  {
    id: 'spas',
    title: 'Custom Spas & Saunas',
    subtitle: 'Bespoke indoor wellness sanctuary engineering',
    icon: 'Waves',
    description: 'Create a personal wellness oasis inside your custom build. We specialize in intricate steam generation connections, high-volume jacuzzi piping, bespoke cedar sauna drainage, and high-efficiency cold-plunge water cooling systems optimized for luxury residential properties.',
    benefits: [
      'Precise steam generator pressure release installation',
      'High-performance plumbing lines for rapid hot/cold cycles',
      'Aesthetic, flush-mount concealed drain grids',
      'Safety-oriented thermal pressure relief valves',
    ],
    process: [
      'Wellness Mechanical Engineering Review',
      'High-Temperature Conduit Layout & Drainage Line Testing',
      'Steam Generator & Thermal System Calibration',
      'Final Thermal Leak and Pressure Testing',
    ],
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=1200',
  },
  {
    id: 'water-systems',
    title: 'Water Filtration & Systems',
    subtitle: 'Pure, mineral-rich soft water throughout your home',
    icon: 'Droplet',
    description: 'Southern Ontario water requires advanced engineering to tackle high hardness levels. We specify and fit luxury commercial-grade water softeners, multi-stage sediment filters, iron/sulfur filtration loops, and premium UV disinfection arrays to protect your luxury fixtures and family health.',
    benefits: [
      'Prolongs the lifetime of expensive luxury fixtures & appliances',
      'Eliminates mineral scale, lime-buildup, and chlorine odors',
      'Low maintenance salt-efficiency auto-calibration loops',
      'Eco-friendly low waste drainage systems',
    ],
    process: [
      'Comprehensive In-Home Raw Water Diagnostics',
      'Hardware Sizing & Filter Media Customization',
      'Bypass Loop Valve Installation for Easy Maintenances',
      'Flow Rate Verification & Post-Softener Quality Analysis',
    ],
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&q=80&w=1200',
  },
  {
    id: 'water-heaters',
    title: 'Water Heaters & Boilers',
    subtitle: 'High-efficiency endless hot water on demand',
    icon: 'Flame',
    description: 'Never run out of hot water again. We install and repair state-of-the-art wall-mounted tankless water heaters and boiler systems from premium brands like Navien and Rinnai. Engineered for maximum energy savings, quiet operations, and instantaneous continuous hot water delivery.',
    benefits: [
      'Saves up to 40% on monthly natural gas or utility bills',
      'Sleek wall-mounted design frees up valuable floor space',
      'Continuous endless hot water loop for dual showers',
      'Red Seal licensed gas lines & ventilation layouts',
    ],
    process: [
      'Hot Water Demand Calculation & Unit Sizing',
      'Licensed Gas Supply and Combustion Vent Configuration',
      'Mounting, Water Conduit Attachment, and Leak Audits',
      'Digital Commissioning, Temperature Set, & User Tutorial',
    ],
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=1200',
  },
  {
    id: 'repairs',
    title: 'Plumbing Services & Repairs',
    subtitle: 'Prompt diagnostic repair by certified Red Seal masters',
    icon: 'Wrench',
    description: 'Plumbing emergencies require immediate, authoritative action. Led by master plumber Adam Van Berkel, our rapid-response diagnostic team addresses water line pipe bursts, stubborn main sewer blockages, leaking plumbing fixtures, backup sump pumps, and fixture retrofits with total precision.',
    benefits: [
      'Available emergency plumbing diagnostic support',
      'High-definition drain camera scopes with footage records',
      'Fully equipped diagnostic service trucks for instant fixes',
      'Upfront transparent flat-rate pricing — no surprise hidden fees',
    ],
    process: [
      'Advanced Diagnostic Assessment & Fault Pinpointing',
      'Immediate Upfront Solid-Pricing Explanation',
      'Flawless Technical Execution of Necessary Fix',
      'Post-Repair Quality Flow Audit & Multi-Point Safeguard Check',
    ],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=1200',
  },
];

export const GALLERY_IMAGES: GalleryItem[] = [
  {
    id: 'gal-11',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-11.jpg',
    title: 'Premium Bathroom Sump & Piping Installation',
    category: 'Renovation',
    size: 'large',
  },
  {
    id: 'gal-10',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-10.jpg',
    title: 'Luxury Back-of-Wall Copper Pipe Fitting',
    category: 'Custom Build',
    size: 'medium',
  },
  {
    id: 'gal-9',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-9-300x225.jpg',
    title: 'Commercial Grade Boiler Valve Connections',
    category: 'Water System',
    size: 'small',
  },
  {
    id: 'gal-3',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-3-300x225.jpg',
    title: 'High-Efficiency Boiler Installation',
    category: 'Water System',
    size: 'small',
  },
  {
    id: 'gal-8',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-8.jpg',
    title: 'Red Seal Bathroom Drain Rough-In',
    category: 'Bathroom',
    size: 'large',
  },
  {
    id: 'gal-7',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-7-300x225.jpg',
    title: 'Modern Kitchen Gas Pipe Assembly',
    category: 'Kitchen',
    size: 'small',
  },
  {
    id: 'gal-5',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-5-300x225.jpg',
    title: 'Multi-Zoned Hydronic Heating Sump Manifold',
    category: 'Custom Build',
    size: 'small',
  },
  {
    id: 'gal-6',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-6-300x225.jpg',
    title: 'Pre-Pour Radiant Floor PEX Pipeline Alignment',
    category: 'Custom Build',
    size: 'medium',
  },
  {
    id: 'gal-4',
    url: 'https://fortifiedplumbing.com/wp-content/uploads/sites/16/2025/10/Fortified-Plumbing-4.jpg',
    title: 'Whole-Home Navien Water Treatment Setup',
    category: 'Water System',
    size: 'large',
  },
];

export const SERVICE_AREAS = [
  {
    city: 'Hamilton',
    region: 'Greater Hamilton Area',
    desc: 'Main servicing zone including core downtown and surrounding escarpment builds.',
    features: ['Custom Home Rough-Ins', 'Emergency Sump Service', 'Water Softeners'],
  },
  {
    city: 'Ancaster',
    region: 'City of Hamilton',
    desc: 'High-end custom bathroom renovations and historic property pipe retrofitting.',
    features: ['Luxury Freestanding Tubs', 'Navien Tankless Heaters', 'Backflow Testing'],
  },
  {
    city: 'Dundas',
    region: 'Valley Community',
    desc: 'Specialist older home copper restoration and high-efficiency heating updates.',
    features: ['Copper Restorations', 'Hydronic Radiant Heating', 'Drain Camera Audits'],
  },
  {
    city: 'Burlington',
    region: 'Halton Region',
    desc: 'Lakefront custom home plumbing installations and multi-zone heating engineering.',
    features: ['Bespoke Steam Showers', 'Main Sewer Line Replacements', 'Commercial Upgrades'],
  },
  {
    city: 'Oakville',
    region: 'Halton Region',
    desc: 'Luxury mansion estate mechanical room builds and wellness sauna plumbing.',
    features: ['Cedar Sauna Drainage', 'Double rainshower assemblies', 'Smart water shutoffs'],
  },
  {
    city: 'Stoney Creek',
    region: 'East Hamilton Community',
    desc: 'New development plumbing layout designs, water heaters, and leak diagnostic services.',
    features: ['Pre-pour PEX layouts', 'High volume sumps', 'Kitchen gas connections'],
  },
];
